### ISSUE TITLE
Gruntfile.js file has some issues

### ISSUE THREAD

**Issue by thebedivere** [bcabanes/generator-frontcow#3]
Some of the options in the Gruntfile.js don't work. 

The options for sass caused issues.

include-paths - should be loadPaths

separator: ';',medias/ - caused an error. I removed the medias/ and it worked.

sourceMap: false - this also caused issues. I just removed the line to get it to work.

output-style - should be style

**Comment by bcabanes** [comment]
Thanks for your returns, you can check-out the new version : https://www.npmjs.com/package/generator-frontcow
